development:
  host: localhost
  adapter: em_postgresql
  database: goliathskel-dev
  pool: 5
  timeout: 5000

production:
  host: localhost
  adapter: em_postgresql
  encoding: utf8
  reconnect: false
  database: goliathskel-prod
  pool: 5
  username: root
  password:

test:
  host: localhost
  adapter: em_postgresql
  database: goliathskel-test
  pool: 5
  timeout: 5000
